language: php
php:
- 7.1
services:
- mysql
- memcached
before_script:
- cp .env.travis .env
- composer self-update
- composer install
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS igniter;'